# Generated by Django 3.2.5 on 2023-04-21 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_accounts_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup', models.CharField(default='', max_length=100)),
                ('drop', models.CharField(default='', max_length=100)),
                ('space', models.IntegerField(default=0)),
                ('contact_num', models.BigIntegerField(default=0)),
                ('fare', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('color', models.CharField(default='#007bff', max_length=20)),
                ('username', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.accounts')),
            ],
        ),
    ]
